"""injury status on players

Revision ID: 0dccb8c24ffc
Revises: d3e31166bcf6
Create Date: 2026-09-23 17:01:31.932163

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0dccb8c24ffc"
down_revision: str | Sequence[str] | None = "d3e31166bcf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """ESPN's injury flag, captured rather than discarded.

    Nullable with no backfill, for the same reason espn_projected_points was:
    the value arrives in the payload the adapter already fetches and was being
    dropped on the floor, so there is nothing to derive it from for rows
    already written. One re-sync per league fills them, and until then the UI
    shows nothing rather than claiming everybody is healthy.
    """
    op.add_column("players", sa.Column("injury_status", sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "injury_status")
    # ### end Alembic commands ###
