"""valuation uncertainty band

Adds valuations.value_sd and .model_sd: the error bar on a value, and the
share of it contributed by this app's own estimators rather than by ESPN.

Both default to 0, which reads as "this row predates the band" rather than
"this row is certain" — a recompute fills them in. No backfill: the numbers
depend on the stat coverage of the run that produced the row, and inventing
them for old rows would assert a confidence nobody measured.

Revision ID: 9616311562d4
Revises: 53fd6f9ca747
Create Date: 2026-09-21 16:29:59.075714

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9616311562d4"
down_revision: str | Sequence[str] | None = "53fd6f9ca747"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "valuations", sa.Column("value_sd", sa.Float(), server_default="0", nullable=False)
    )
    op.add_column(
        "valuations", sa.Column("model_sd", sa.Float(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("valuations", "model_sd")
    op.drop_column("valuations", "value_sd")
    # ### end Alembic commands ###
