"""marginal replacement basis

Adds 'marginal' to the replacement_basis enum: value measured as what the
league loses when a player is removed and the best eligible bench player takes
their seat. See valuation/engine.py.

Revision ID: a1c4e7b90f22
Revises: 9616311562d4
Create Date: 2026-09-21 17:05:00.000000

"""

from collections.abc import Sequence

from alembic import op

revision: str = "a1c4e7b90f22"
down_revision: str | Sequence[str] | None = "9616311562d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ALTER TYPE ... ADD VALUE cannot run inside a transaction block on older
    # servers, and Alembic wraps migrations in one. IF NOT EXISTS keeps this
    # idempotent; COMMIT first releases the wrapping transaction.
    op.execute("COMMIT")
    op.execute("ALTER TYPE replacement_basis ADD VALUE IF NOT EXISTS 'marginal'")


def downgrade() -> None:
    """Downgrade schema.

    Postgres cannot drop a value from an enum, so the type is rebuilt without
    it. Any league sitting on 'marginal' falls back to 'starter' — the basis
    is a modelling choice, not data, and the valuations it produced are
    regenerated by a recompute either way.
    """
    op.execute(
        "UPDATE leagues SET replacement_basis = 'starter' WHERE replacement_basis = 'marginal'"
    )
    op.execute("ALTER TYPE replacement_basis RENAME TO replacement_basis_old")
    op.execute("CREATE TYPE replacement_basis AS ENUM ('starter', 'waiver')")
    # The server_default has to come off and go back on around the swap:
    # Postgres refuses to cast an existing default to the new type, and the
    # error it gives ("default for column ... cannot be cast automatically")
    # names the column rather than the default, which sends you looking in
    # the wrong place.
    op.execute("ALTER TABLE leagues ALTER COLUMN replacement_basis DROP DEFAULT")
    op.execute(
        "ALTER TABLE leagues ALTER COLUMN replacement_basis TYPE replacement_basis "
        "USING replacement_basis::text::replacement_basis"
    )
    op.execute("ALTER TABLE leagues ALTER COLUMN replacement_basis SET DEFAULT 'starter'")
    op.execute("DROP TYPE replacement_basis_old")
