"""espn projected points on players

Revision ID: d3e31166bcf6
Revises: a1c4e7b90f22
Create Date: 2026-09-23 16:14:42.424498

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3e31166bcf6"
down_revision: str | Sequence[str] | None = "a1c4e7b90f22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """ESPN's own projected fantasy total, kept alongside the raw stat line.

    Nullable with no backfill, deliberately. The value arrives in the same ESPN
    payload as everything else in `projections` and was simply being discarded,
    so there is nothing to compute it FROM for rows already written — one
    re-sync per league fills them. Until then simulate(bot_valuation="espn")
    raises NoEspnProjections naming /sync, which is a better answer than a
    column full of zeros that reads as "ESPN rates everyone at nothing".
    """
    op.add_column("players", sa.Column("espn_projected_points", sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "espn_projected_points")
    # ### end Alembic commands ###
