// Writes out/_headers after `next build`.
//
// Cloudflare Pages reads a plain-text `_headers` file from the root of the
// published directory and applies it to every matching response. This is the
// only way a static export can send security headers at all: `output: "export"`
// disables the headers() block in next.config.ts (there is no server left to
// run it), so without this file the site ships with none.
//
// Generated rather than committed to public/ because Content-Security-Policy
// has to name the API's origin in connect-src, and that origin is
// NEXT_PUBLIC_API_URL — a build-time input. A checked-in file would either
// hardcode one environment's API or have to fall back to `connect-src *`,
// which gives up the one CSP directive that actually constrains this app.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "out");

const apiUrl = process.env.NEXT_PUBLIC_API_URL;
if (!apiUrl) {
  // next.config.ts already refuses a production build without this, so
  // reaching here means the script was run on its own. Fail rather than emit a
  // policy that quietly omits the API and breaks every request on the site.
  throw new Error("NEXT_PUBLIC_API_URL is not set — cannot write connect-src.");
}
const apiOrigin = new URL(apiUrl).origin;

// Player headshots. The only third-party origin the app loads anything from;
// see src/lib/espn.ts.
const IMAGE_CDN = "https://a.espncdn.com";

const csp = [
  "default-src 'self'",
  // No <base> is emitted, and allowing one lets injected markup re-point every
  // relative URL on the page.
  "base-uri 'self'",
  "object-src 'none'",
  // The app is never meant to be framed. frame-ancestors is the modern form;
  // X-Frame-Options below is the same statement for older browsers.
  "frame-ancestors 'none'",
  "form-action 'self'",
  `img-src 'self' data: ${IMAGE_CDN}`,
  // next/font/google self-hosts at build time — the .woff2 files are served
  // from /_next/static/media, so no Google origin is needed at runtime.
  "font-src 'self'",
  // 'unsafe-inline' for styles: prerendered pages carry style="" attributes
  // from React's inline style props.
  "style-src 'self' 'unsafe-inline'",
  // 'unsafe-inline' for scripts, and this is the policy's real limit. Next's
  // App Router emits an inline bootstrap script (self.__next_f.push(...)) into
  // every prerendered page, and the nonce mechanism that would replace this
  // needs a server to generate one per response — which `output: "export"`
  // does not have. Dropping it breaks hydration on every page. The directive
  // still blocks scripts from other ORIGINS, which is the larger half.
  "script-src 'self' 'unsafe-inline'",
  // The directive that earns the generated file: the app may talk to its own
  // API and nothing else.
  `connect-src 'self' ${apiOrigin}`,
].join("; ");

const headers = `# Generated by scripts/write-headers.mjs — do not edit by hand.
# Regenerated on every build; edit the script instead.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  Cross-Origin-Opener-Policy: same-origin

# Hashed filenames, so these are safe to cache forever. Everything else falls
# back to Cloudflare's default, which revalidates — right for the HTML, since a
# stale index.html would keep pointing at chunks the last deploy removed.
/_next/static/*
  Cache-Control: public, max-age=31536000, immutable
`;

mkdirSync(out, { recursive: true });
writeFileSync(join(out, "_headers"), headers);
console.log(`wrote out/_headers (connect-src ${apiOrigin})`);
