/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leagues */
        get: operations["list_leagues_leagues_get"];
        put?: never;
        /** Create League */
        post: operations["create_league_leagues_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get League */
        get: operations["get_league_leagues__league_id__get"];
        put?: never;
        post?: never;
        /** Delete League */
        delete: operations["delete_league_leagues__league_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync League */
        post: operations["sync_league_leagues__league_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description The league's cached pool with this league's valuations attached.
         */
        get: operations["list_players_leagues__league_id__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/valuations/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Valuations
         * @description Run the engine over the cached pool and persist the results.
         *
         *     Owner only (SPEC 4): it overwrites reference data every share-holder reads.
         *     Takes no data source — the engine values the CACHED pool, so this endpoint
         *     never touches ESPN and a stale pool is fixed with /sync, not here.
         */
        post: operations["compute_valuations_leagues__league_id__valuations_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{league_id}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Valuations
         * @description The engine's output for this league, best first.
         */
        get: operations["list_valuations_leagues__league_id__valuations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Boards
         * @description Boards the caller owns, plus boards shared with them.
         */
        get: operations["list_boards_boards_get"];
        put?: never;
        /** Create Board */
        post: operations["create_board_boards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Board */
        get: operations["get_board_boards__board_id__get"];
        put?: never;
        post?: never;
        /** Delete Board */
        delete: operations["delete_board_boards__board_id__delete"];
        options?: never;
        head?: never;
        /** Patch Board */
        patch: operations["patch_board_boards__board_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rankings */
        get: operations["list_rankings_boards__board_id__rankings_get"];
        put?: never;
        /** Create Ranking */
        post: operations["create_ranking_boards__board_id__rankings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings/{ranking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Ranking */
        delete: operations["delete_ranking_rankings__ranking_id__delete"];
        options?: never;
        head?: never;
        /** Patch Ranking */
        patch: operations["patch_ranking_rankings__ranking_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/rankings/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Rankings
         * @description Bulk reorder, all or nothing.
         *
         *     A batch naming a player with no ranking on this board changes nothing at
         *     all: a half-applied reorder would leave the board in an order the user never
         *     asked for and cannot easily undo.
         */
        patch: operations["reorder_rankings_boards__board_id__rankings_reorder_patch"];
        trace?: never;
    };
    "/boards/{board_id}/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tiers */
        get: operations["list_tiers_boards__board_id__tiers_get"];
        put?: never;
        /** Create Tier */
        post: operations["create_tier_boards__board_id__tiers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}/tiers/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autotier
         * @description Seed this board's tiers from the league's computed values (SPEC 5.4).
         *
         *     Not in SPEC 4's endpoint list, which simply does not enumerate it — SPEC 5.4
         *     and SPEC 8 both call for the feature. It has to be board-scoped, because
         *     tiers are, which is why it cannot hang off the league-scoped compute route.
         *
         *     DESTRUCTIVE: it replaces the board's existing tiers. Rankings survive with
         *     their tier_id reassigned, and user_rank, notes and flags are never touched.
         *
         *     "/tiers/auto" does not collide with "/tiers": FastAPI matches whole paths
         *     and a path parameter never spans a slash.
         */
        post: operations["autotier_boards__board_id__tiers_auto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiers/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tier */
        delete: operations["delete_tier_tiers__tier_id__delete"];
        options?: never;
        head?: never;
        /** Patch Tier */
        patch: operations["patch_tier_tiers__tier_id__patch"];
        trace?: never;
    };
    "/boards/{board_id}/mocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mocks */
        get: operations["list_mocks_boards__board_id__mocks_get"];
        put?: never;
        /**
         * Create Mock
         * @description Create a mock and lay out its whole board of empty picks.
         *
         *     The picks exist from creation because SPEC 4 sets a player ON a pick_number
         *     rather than appending one, and mock_picks.player_id is nullable precisely
         *     so an undrafted slot has somewhere to be.
         */
        post: operations["create_mock_boards__board_id__mocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{mock_id}/picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Picks
         * @description The draft board, in pick order, with the player on each filled slot.
         *
         *     Not in SPEC 4, which describes setting a pick and asking what is left but
         *     never reading the board back — so a UI could record picks and have no way
         *     to show them.
         *
         *     The player is nested rather than left as a bare id, and that is the whole
         *     difference between a board and a list of UUIDs. A drafted player is by
         *     definition absent from best-available, so a client joining the two has
         *     nowhere to look the name up and can only print the id.
         *
         *     selectinload, not lazy loading: this returns every slot on the board —
         *     130 rows for a 10-team, 13-round league — and each one touching `player`
         *     on access is 130 queries for one screen.
         */
        get: operations["list_picks_mocks__mock_id__picks_get"];
        put?: never;
        /**
         * Set Pick
         * @description Record a pick, or clear one by sending player_id null.
         */
        post: operations["set_pick_mocks__mock_id__picks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{mock_id}/best-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Best Available
         * @description Everyone still on the board, best first — the "who should I take" view.
         */
        get: operations["best_available_mocks__mock_id__best_available_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{mock_id}/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recommendation
         * @description Who to take now, re-valued against the board as it stands.
         *
         *     best-available sorts by a preseason number: the pool it was computed over
         *     no longer exists by the third round. This endpoint recomputes each slot's
         *     replacement level against the UNDRAFTED pool and the seats still unfilled
         *     league-wide, so a position that has been run on lifts the players left in
         *     it — which is the difference between a ranking and a recommendation.
         *
         *     Read-only. Nothing here touches the valuations cache; see
         *     services/recommendation.py for why that matters.
         */
        get: operations["recommendation_mocks__mock_id__recommendation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{mock_id}/lineup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lineup
         * @description Your own roster in this mock, auto-assigned to the league's slots.
         *
         *     Board access, not edit: a shared board's owner should be able to look at
         *     the lineup their draft is producing without being able to change it.
         *
         *     The assignment comes from valuation/draft.py rather than being recomputed
         *     here, so the seats shown always agree with the seats the replacement-level
         *     maths thinks are taken.
         */
        get: operations["lineup_mocks__mock_id__lineup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mocks/{mock_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Picks
         * @description Auto-draft the other teams up to your next pick.
         *
         *     Edit access, not board access: unlike every other mock read this writes
         *     picks, so a read-only share must not be able to run it.
         *
         *     Already-filled slots are skipped rather than redrafted, so calling this
         *     twice is safe and never overwrites a pick you made yourself.
         */
        post: operations["simulate_picks_mocks__mock_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{board_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shares */
        get: operations["list_shares_boards__board_id__shares_get"];
        put?: never;
        /** Create Share */
        post: operations["create_share_boards__board_id__shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shares/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Share */
        delete: operations["delete_share_shares__share_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness — the one endpoint that never needs auth or a DB.
         *
         *     Answering means the process is up and the threadpool is not exhausted.
         *     It deliberately says nothing about whether the database is reachable;
         *     that is /ready's job, and conflating them turns a database blip into a
         *     machine restart.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness — can this instance serve a real request?
         *
         *     SELECT 1 through the same pool every route uses, so this fails for the
         *     same reasons they would: no database, exhausted pool, dead connection.
         *     503 rather than an exception, because a readiness probe that 500s is
         *     indistinguishable from one that crashed.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AutoTierIn
         * @description Knobs for the auto-tiering gap-split (SPEC 5.4).
         *
         *     Both fields default, so `{}` is a valid body — the common case is "just
         *     tier it". pool_size caps how deep down the value list to bother grouping:
         *     past a certain point every player is replacement-level and a tier boundary
         *     between them says nothing.
         */
        AutoTierIn: {
            /**
             * N Tiers
             * @default 8
             */
            n_tiers: number;
            /**
             * Pool Size
             * @default 60
             */
            pool_size: number;
        };
        /**
         * BestAvailableOut
         * @description A pool player, their valuation, and what this board says about them.
         *
         *     Inherits player + valuation so the "who should I take" view and
         *     GET /leagues/{id}/players stay one shape plus a field, rather than two the
         *     frontend has to special-case.
         */
        BestAvailableOut: {
            player: components["schemas"]["PlayerOut"];
            valuation: components["schemas"]["ValuationOut"] | null;
            ranking: components["schemas"]["RankingOut"] | null;
        };
        /** BoardCreate */
        BoardCreate: {
            /**
             * League Id
             * Format: uuid
             */
            league_id: string;
            /** Name */
            name: string;
        };
        /** BoardOut */
        BoardOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * League Id
             * Format: uuid
             */
            league_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BoardPatch */
        BoardPatch: {
            /** Name */
            name?: string | null;
        };
        /**
         * BotValuation
         * @description Whose opinion of a player the simulated teams draft on.
         *
         *     ENGINE  this app's projections, reconciled against the league's scoring by
         *             stats.py and cached on `valuations`.
         *     ESPN    ESPN's own projected fantasy total, already scored under this
         *             league's settings and stored on `players.espn_projected_points`.
         *
         *     Not stored on the mock. It changes who the bots take, not what the board
         *     means, and re-running a mock with the other setting is the comparison
         *     worth having rather than a migration.
         * @enum {string}
         */
        BotValuation: "engine" | "espn";
        /**
         * ComputeIn
         * @description Optional knobs for a recompute. `{}` reuses the league's own settings.
         *
         *     Setting `replacement_basis` PERSISTS it on the league rather than applying
         *     it for one call. That is deliberate: it changes what every row in
         *     `valuations` means, and a cache whose rows cannot say which question they
         *     answer is worse than no cache.
         */
        ComputeIn: {
            replacement_basis?: components["schemas"]["ReplacementBasis"] | null;
        };
        /**
         * ComputeResult
         * @description What the write did, not what it wrote — same shape as league.SyncResult.
         *
         *     `coverage` and `estimated_share` are the honesty of the number. ESPN projects
         *     only 31 of its 46 scoreable stat codes, so a league can score things that are
         *     never projected; without this the valuation would look equally confident
         *     whether every stat was real or a third of the scoring was invented.
         */
        ComputeResult: {
            /** Players Valued */
            players_valued: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            replacement_basis: components["schemas"]["ReplacementBasis"];
            /** Coverage */
            coverage: components["schemas"]["StatCoverageOut"][];
            /** Estimated Share */
            estimated_share: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeagueCreate */
        LeagueCreate: {
            /** Espn League Id */
            espn_league_id: number;
            /** Season */
            season: number;
            /** Name */
            name: string;
            /** Espn S2 */
            espn_s2?: string | null;
        };
        /** LeagueOut */
        LeagueOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Espn League Id */
            espn_league_id: number;
            /** Season */
            season: number;
            /** Name */
            name: string;
            scoring_format: components["schemas"]["ScoringFormat"];
            /** Num Teams */
            num_teams: number;
            /** Roster Size */
            roster_size: number;
            /** Roster Slots */
            roster_slots: {
                [key: string]: number;
            };
            /** Point Weights */
            point_weights: {
                [key: string]: number;
            };
            replacement_basis: components["schemas"]["ReplacementBasis"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * LineupOut
         * @description Your roster in a mock, laid out over the league's slots.
         *
         *     `bench` holds players who fit no open starting slot — a roster spot with no
         *     lineup spot. `bench_size` is roster_size minus the starting slots, which is
         *     derived rather than stored because roster_slots counts starters only.
         */
        LineupOut: {
            /** My Draft Slot */
            my_draft_slot: number;
            /** Roster Size */
            roster_size: number;
            /** Starters */
            starters: components["schemas"]["SeatOut"][];
            /** Bench */
            bench: components["schemas"]["PlayerOut"][];
            /** Bench Size */
            bench_size: number;
            /** Picks Made */
            picks_made: number;
            /** Picks Remaining */
            picks_remaining: number;
        };
        /**
         * LiveValueOut
         * @description A player's value against the draft board as it stands, not the preseason.
         *
         *     Separate from `valuation` rather than replacing it: the preseason number is
         *     the baseline the shift is measured against, so a UI that wants to say "up
         *     90 since pick 1" needs both in the same payload.
         */
        LiveValueOut: {
            /** Value */
            value: number;
            /** Replacement Points */
            replacement_points: number;
            /** Assigned Slot */
            assigned_slot: string;
            /** Replacement Shift */
            replacement_shift: number;
            /** Value Change */
            value_change: number;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MadePickOut */
        MadePickOut: {
            /** Pick Number */
            pick_number: number;
            /** Team Slot */
            team_slot: number;
            player: components["schemas"]["PlayerOut"];
        };
        /** MockCreate */
        MockCreate: {
            /** Name */
            name: string;
            /** My Draft Slot */
            my_draft_slot: number;
        };
        /**
         * MockWithProgressOut
         * @description MockOut plus how far the draft has got.
         *
         *     Both counts come from one grouped query over mock_picks, so listing a
         *     board's mocks stays a single round trip rather than one per mock.
         */
        MockWithProgressOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Board Id
             * Format: uuid
             */
            board_id: string;
            /** Name */
            name: string;
            /** My Draft Slot */
            my_draft_slot: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Picks Total */
            picks_total: number;
            /** Picks Made */
            picks_made: number;
        };
        /** Page[BestAvailableOut] */
        Page_BestAvailableOut_: {
            /** Items */
            items: components["schemas"]["BestAvailableOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[PlayerWithValuationOut] */
        Page_PlayerWithValuationOut_: {
            /** Items */
            items: components["schemas"]["PlayerWithValuationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[ValuationOut] */
        Page_ValuationOut_: {
            /** Items */
            items: components["schemas"]["ValuationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PickOut */
        PickOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mock Draft Id
             * Format: uuid
             */
            mock_draft_id: string;
            /** Pick Number */
            pick_number: number;
            /** Round */
            round: number;
            /** Team Slot */
            team_slot: number;
            /** Is Mine */
            is_mine: boolean;
            /** Player Id */
            player_id: string | null;
        };
        /**
         * PickSet
         * @description Record one pick, or clear it by sending player_id null.
         *
         *     Clearing is not in SPEC 4, which only describes setting a pick; undoing a
         *     misclick mid-mock is the obvious need and the column is already nullable.
         */
        PickSet: {
            /** Pick Number */
            pick_number: number;
            /** Player Id */
            player_id?: string | null;
        };
        /**
         * PickWithPlayerOut
         * @description A pick with the player on it, for reading the board back.
         *
         *     PickOut carries player_id and nothing else, which is right for the write
         *     (you send an id, you get the id back) and useless for the read: a drafted
         *     player is by definition absent from best-available, so a client has no
         *     other source for the name and can only render the raw UUID.
         *
         *     None when the slot is empty, which is most of the board before the draft
         *     starts — mock_picks rows are created at mock creation with player_id NULL.
         */
        PickWithPlayerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mock Draft Id
             * Format: uuid
             */
            mock_draft_id: string;
            /** Pick Number */
            pick_number: number;
            /** Round */
            round: number;
            /** Team Slot */
            team_slot: number;
            /** Is Mine */
            is_mine: boolean;
            /** Player Id */
            player_id: string | null;
            player: components["schemas"]["PlayerOut"] | null;
        };
        /** PlayerOut */
        PlayerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Espn Player Id */
            espn_player_id: number;
            /** Season */
            season: number;
            /** Name */
            name: string;
            /** Pro Team */
            pro_team: string;
            /** Positions */
            positions: string[];
            /** Projections */
            projections: {
                [key: string]: number;
            };
            /** Injury Status */
            injury_status?: string | null;
        };
        /**
         * PlayerSort
         * @description SPEC 4 says "sort by value or rank", but there is no league-scoped rank:
         *     rankings.user_rank is board-scoped and this endpoint knows only a league,
         *     and ESPN's own rank is not stored. `value` IS that ordinal.
         * @enum {string}
         */
        PlayerSort: "value" | "projected_points" | "name";
        /**
         * PlayerWithValuationOut
         * @description A pool player plus this league's valuation, which may be absent.
         *
         *     `valuation` is None until POST /valuations/compute has run. The pool is
         *     synced from ESPN and valued separately, so "synced but not yet valued" is a
         *     normal state the UI has to render rather than an error.
         *
         *     No from_attributes here: the route builds this from a (Player, Valuation |
         *     None) row pair, and from_attributes on the two inner models is what lets
         *     the ORM objects validate into these fields.
         */
        PlayerWithValuationOut: {
            player: components["schemas"]["PlayerOut"];
            valuation: components["schemas"]["ValuationOut"] | null;
        };
        /**
         * Position
         * @description The five real positions — the only values a SQL filter can match.
         *
         *     ESPN's flex slots (G, F) and combo slots (PF/C) are ENGINE vocabulary:
         *     data_source.positions_of keeps only these five on the players row, so
         *     filtering the column for "G" finds nobody. Flex filtering would have to
         *     expand to a set of these before it reached SQL.
         * @enum {string}
         */
        Position: "PG" | "SG" | "SF" | "PF" | "C";
        /** RankingCreate */
        RankingCreate: {
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** User Rank */
            user_rank?: number | null;
            /** Tier Id */
            tier_id?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Is Target
             * @default false
             */
            is_target: boolean;
            /**
             * Is Avoid
             * @default false
             */
            is_avoid: boolean;
        };
        /** RankingOut */
        RankingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Board Id
             * Format: uuid
             */
            board_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** Tier Id */
            tier_id: string | null;
            /** User Rank */
            user_rank: number | null;
            /** Note */
            note: string | null;
            /** Is Target */
            is_target: boolean;
            /** Is Avoid */
            is_avoid: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RankingPatch
         * @description Every field optional: PATCH must not blank what it does not mention.
         *
         *     `model_fields_set` is what distinguishes "note omitted" from "note cleared
         *     to null", so routes apply this with exclude_unset=True.
         */
        RankingPatch: {
            /** User Rank */
            user_rank?: number | null;
            /** Tier Id */
            tier_id?: string | null;
            /** Note */
            note?: string | null;
            /** Is Target */
            is_target?: boolean | null;
            /** Is Avoid */
            is_avoid?: boolean | null;
        };
        /**
         * RecommendationOut
         * @description A best-available row plus its live, draft-aware re-valuation.
         *
         *     Inherits rather than replaces so the mock screen can render one shape:
         *     best-available and the recommendation differ by a field, not a schema.
         */
        RecommendationOut: {
            player: components["schemas"]["PlayerOut"];
            valuation: components["schemas"]["ValuationOut"] | null;
            ranking: components["schemas"]["RankingOut"] | null;
            live: components["schemas"]["LiveValueOut"];
            /** Marginal Value */
            marginal_value: number;
            /** Lineup Delta */
            lineup_delta: number;
            /** Improves Lineup */
            improves_lineup: boolean;
            /** Fills Open Seat */
            fills_open_seat: boolean;
            /** Survival */
            survival: number;
            /** Expected Next */
            expected_next: number;
            /** Score */
            score: number;
        };
        /**
         * RecommendationPage
         * @description A page of recommendations plus the draft context they assume.
         *
         *     `picks_until_next` is what every survival number is conditioned on, so it
         *     travels with them: the same board reads completely differently at the turn
         *     (nobody picks in between) and in the middle of a round (nine do).
         */
        RecommendationPage: {
            /** Items */
            items: components["schemas"]["RecommendationOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Picks Until Next */
            picks_until_next: number;
        };
        /**
         * RecommendationSort
         * @description How to order the recommendation.
         *
         *     SCORE is the default and the most complete answer: what your next two
         *     picks are worth together, so a player who will still be there when the
         *     wheel comes back is worth less of THIS pick. MARGINAL ignores timing and
         *     asks only "best for my roster now"; VALUE is the league-wide order with
         *     your roster ignored too. All three are kept because the later ones lean
         *     on a model of the field, and being able to drop back to the plainer
         *     number is how you tell whether that model is helping.
         * @enum {string}
         */
        RecommendationSort: "score" | "marginal" | "value" | "confident";
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ReorderIn */
        ReorderIn: {
            /** Items */
            items: components["schemas"]["ReorderItem"][];
        };
        /** ReorderItem */
        ReorderItem: {
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** User Rank */
            user_rank: number;
        };
        /**
         * ReplacementBasis
         * @description What this league's valuations measure a player against.
         *
         *     Mirrors valuation.engine.ReplacementBasis. Stored per league rather than
         *     read from config because it changes what every cached number in
         *     `valuations` MEANS — a board computed one way and read the other is
         *     silently wrong, and there would be nothing in the row to say so.
         * @enum {string}
         */
        ReplacementBasis: "starter" | "waiver" | "marginal";
        /**
         * ScoringFormat
         * @enum {string}
         */
        ScoringFormat: "points" | "categories";
        /**
         * SeatOut
         * @description One starting slot, filled or empty.
         *
         *     An empty seat is a row in the response rather than an omission: "you still
         *     need a centre" is the most useful thing this endpoint says, and a client
         *     cannot infer it from a list of who you have.
         */
        SeatOut: {
            /** Slot */
            slot: string;
            /** Index */
            index: number;
            player: components["schemas"]["PlayerOut"] | null;
        };
        /** ShareCreate */
        ShareCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            permission: components["schemas"]["SharePermission"];
        };
        /** ShareOut */
        ShareOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Board Id
             * Format: uuid
             */
            board_id: string;
            /**
             * Shared With User Id
             * Format: uuid
             */
            shared_with_user_id: string;
            permission: components["schemas"]["SharePermission"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SharePermission
         * @enum {string}
         */
        SharePermission: "read" | "edit";
        /**
         * SimulateIn
         * @description Knobs for auto-drafting the other teams. `{}` is the common case.
         *
         *     `reach` is how far down its shortlist a simulated team will go: 1 makes
         *     every bot a pure value-maximizer, which produces a defensible board and
         *     the identical draft every time. The default of 3 keeps the best player the
         *     most likely pick while letting the board differ run to run, which is the
         *     only way repeated mocks tell you anything.
         */
        SimulateIn: {
            /**
             * Reach
             * @default 3
             */
            reach: number;
            /** Seed */
            seed?: number | null;
            /**
             * Stop At My Pick
             * @default true
             */
            stop_at_my_pick: boolean;
            /** @default engine */
            bot_valuation: components["schemas"]["BotValuation"];
        };
        /**
         * SimulateOut
         * @description What the simulation did, and whose turn it is now.
         */
        SimulateOut: {
            /** Picks */
            picks: components["schemas"]["MadePickOut"][];
            /** Next Pick Number */
            next_pick_number: number | null;
            /** Next Is Mine */
            next_is_mine: boolean;
            /** Board Complete */
            board_complete: boolean;
        };
        /**
         * StatCoverageOut
         * @description How one scored stat was obtained, and how much of the scoring it carries.
         */
        StatCoverageOut: {
            /** Stat */
            stat: string;
            /** Weight */
            weight: number;
            /** Provenance */
            provenance: string;
            /** Detail */
            detail: string;
            /** Point Share */
            point_share: number;
        };
        /** SyncResult */
        SyncResult: {
            /** Players Synced */
            players_synced: number;
            scoring_format: components["schemas"]["ScoringFormat"];
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /** TierCreate */
        TierCreate: {
            /** Label */
            label: string;
            /** Color */
            color?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** TierOut */
        TierOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Board Id
             * Format: uuid
             */
            board_id: string;
            /** Label */
            label: string;
            /** Color */
            color: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /**
         * TierPatch
         * @description Every field optional: PATCH must not blank what it does not mention.
         *
         *     Same contract as RankingPatch — `color: str | None = None` cannot on its own
         *     tell "color omitted" from "color cleared to null", so the route applies this
         *     with exclude_unset=True and reads model_fields_set rather than the values.
         */
        TierPatch: {
            /** Label */
            label?: string | null;
            /** Color */
            color?: string | null;
            /** Sort Order */
            sort_order?: number | null;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuationOut */
        ValuationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * League Id
             * Format: uuid
             */
            league_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** Projected Points */
            projected_points: number;
            /** Replacement Points */
            replacement_points: number;
            /** Value */
            value: number;
            /** Assigned Slot */
            assigned_slot: string;
            /** Value Sd */
            value_sd: number;
            /** Model Sd */
            model_sd: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_leagues_leagues_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueOut"][];
                };
            };
        };
    };
    create_league_leagues_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeagueCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_league_leagues__league_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_league_leagues__league_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_league_leagues__league_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_leagues__league_id__players_get: {
        parameters: {
            query?: {
                position?: components["schemas"]["Position"] | null;
                sort?: components["schemas"]["PlayerSort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlayerWithValuationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_valuations_leagues__league_id__valuations_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ComputeIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_valuations_leagues__league_id__valuations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                league_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ValuationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_boards_boards_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"][];
                };
            };
        };
    };
    create_board_boards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_board_boards__board_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_board_boards__board_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_board_boards__board_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoardPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rankings_boards__board_id__rankings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ranking_boards__board_id__rankings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ranking_rankings__ranking_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ranking_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_ranking_rankings__ranking_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ranking_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_rankings_boards__board_id__rankings_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tiers_boards__board_id__tiers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_tier_boards__board_id__tiers_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autotier_boards__board_id__tiers_auto_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoTierIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tier_tiers__tier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tier_tiers__tier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TierPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mocks_boards__board_id__mocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockWithProgressOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mock_boards__board_id__mocks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MockWithProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_picks_mocks__mock_id__picks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickWithPlayerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pick_mocks__mock_id__picks_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PickSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PickOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    best_available_mocks__mock_id__best_available_get: {
        parameters: {
            query?: {
                position?: components["schemas"]["Position"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BestAvailableOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendation_mocks__mock_id__recommendation_get: {
        parameters: {
            query?: {
                position?: components["schemas"]["Position"] | null;
                sort?: components["schemas"]["RecommendationSort"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lineup_mocks__mock_id__lineup_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_picks_mocks__mock_id__simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mock_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shares_boards__board_id__shares_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_boards__board_id__shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                board_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_share_shares__share_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
